spring:
  datasource:
    url: ${QUERY_AI_DB_URL}
    username: ${QUERY_AI_DB_USERNAME}
    password: ${QUERY_AI_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base_url: ${OPENAI_BASE_URL:https://openrouter.ai/api}
      chat:
        model: deepseek/deepseek-r1:free
        #model: deepseek/deepseek-chat

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.ai: DEBUG