spring:
  datasource:
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    url: ${QUERY_AI_DB_URL:jdbc:postgresql://localhost:5432/employeedb}
    username: ${QUERY_AI_DB_USERNAME:aiquery}
    password: ${QUERY_AI_DB_PASSWORD:AI@Query2025}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: ${QUERY_AI_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: update
      data-locations: src/main/resources/data.sql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
      data-locations: classpath:data.sql

  ai:
    mistralai:
      api-key: ${MISTRAL_API_KEY:default}
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base_url: ${OPENAI_BASE_URL:https://openrouter.ai/api}
      chat:
        model: deepseek/deepseek-r1:free
        client:
          enabled: true

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.ai: DEBUG