spring:
  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base_url: ${OPENAI_BASE_URL:https://openrouter.ai/api}
      chat:
        model: deepseek/deepseek-r1:free
        #model: deepseek/deepseek-chat

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.ai: DEBUG